# Setup
title:        Geospatial Grids (GeoGrids)
tagline:      CPC geospatial grids (grid definitions, interpolation, etc.)
baseurl:      /cpc.geogrids

# About/contact
author:
  name:       Mike Charles
  url:        http://www.github.com/mikecharles

#Others
markdown: kramdown
